# Generated by Django 4.0.3 on 2022-05-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_imagen_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagen',
        ),
    ]
